version: '3.8'
services:
  db:
    container_name: viva-comercio
    image: postgres:15-alpine
    restart: "unless-stopped"
    env_file:
      - .env
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGCLIENTENCODING: UTF8
    ports:
      - "5433:5432"